FROM python:3.10

# update and upgrade
RUN apt -y update
RUN apt -y upgrade

RUN mkdir /workspace
WORKDIR /workspace

COPY . .

RUN make install_rust
RUN make venv_create
RUN make rust_workers


CMD ["make", "start_development"]
EXPOSE 8000
