ARG PYTHON_VERSION

FROM python:${PYTHON_VERSION}
ARG AIRFLOW_PROJ_DIR

RUN pip install poetry
RUN mkdir /$AIRFLOW_PROJ_DIR
WORKDIR $AIRFLOW_PROJ_DIR
COPY ./$AIRFLOW_PROJ_DIR/scripts/poetry.lock poetry.lock
COPY ./$AIRFLOW_PROJ_DIR/scripts/pyproject.toml pyproject.toml
RUN poetry install

ENTRYPOINT ["poetry", "run","airflow"]
CMD ["standalone"]
