FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

# update and upgrade
RUN apt -y update
RUN apt -y upgrade


RUN mkdir /workspace
WORKDIR /workspace

COPY . .
RUN rm .env

RUN make install_rust
RUN make venv_create
RUN make rust_workers

CMD ["make", "start_production"]
EXPOSE 8000
