FROM apache/spark-py

USER root

# RUN mkdir -p /opt/spark/logs && chmod a+wr /opt/spark/logs
# RUN mkdir -p /opt/spark/work && chmod a+wr /opt/spark/work

WORKDIR /opt/spark/work

RUN apt update && apt install -y iputils-ping

ENV SPARK_NO_DAEMONIZE=true

CMD ["/opt/spark/sbin/start-master.sh"]
