---
version: '3.8'
services:

    spark-master:
        image: apache/spark-py
        ports:
            - 9090:8080
            - 7077:7077
        volumes:
            - ./spark-apps:/opt/spark-apps
            - ./spark-data:/opt/spark-data
        environment:
            SPARK_LOCAL_IP: spark-masterark-master
            SPARK_WORKLOAD: masterascasc
            SPARK_MODE: master
        command: sleep infinity
        networks:
            - shared_network

    spark-worker:
        image: apache/spark-py
        volumes:
            - ./spark-apps:/opt/spark-apps
            - ./spark-data:/opt/spark-data
        environment:
            SPARK_MASTER: spark://spark-master:7077
            SPARK_MODE: worker
        networks:
            - shared_network
