---
version: '3.8'
services:

    spark-master:
        build:
            context: .
            dockerfile: Dockerfile-spark
        hostname: spark-master
        ports:
            - 9090:8080
            - 7077:7077
        volumes:
            - ./spark-apps:/opt/spark-apps
            - ./spark-data:/opt/spark-data
        environment:
            SPARK_LOCAL_IP: spark-master
            SPARK_WORKLOAD: master
            SPARK_MODE: master
        networks:
            - shared_network

    spark-worker:
        scale: 2
        build:
            context: .
            dockerfile: Dockerfile-spark
        volumes:
            - ./spark-apps:/opt/spark-apps
            - ./spark-data:/opt/spark-data
        command: /opt/spark/sbin/start-worker.sh spark-master:7077
        environment:
            SPARK_MASTER: spark://spark-master:7077
            SPARK_MODE: worker
        networks:   
            - shared_network
