---
version: '3.7'

services:

    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backend
        image: fast-api-full
        hostname: backend
        restart: on-failure
        ports:
            - 127.0.0.1:8000:8000
        volumes:
            - .:/workspace
        command: >
            sh -c "sleep infinity"
        networks:
            - shared_network

    db:
        image: postgres:10-alpine
        container_name: db
        hostname: ${POSTGRES_HOST}
        ports:
            - 127.0.0.1:5432:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        networks:
            - shared_network

    redis:
        image: redis:latest
        container_name: redis
        hostname: ${REDIS_HOST}
        ports:
            - 127.0.0.1:6379:6379
        networks:
            - shared_network

    rabbitmq:
        image: rabbitmq:latest
        container_name: rabbitmq
        hostname: ${RABBITMQ_HOST}
        ports:
            - 127.0.0.1:5672:5672
        networks:
            - shared_network

    phppgadmin:
        image: docker.io/bitnami/phppgadmin
        ports:
            - 127.0.0.1:8081:8080
        volumes:
            - pgadmin:/var/lib/pgadmin
        environment:
            - DATABASE_HOST=${POSTGRES_HOST}
        depends_on:
            - db
        networks:
            - shared_network

volumes:
    postgres-data:
    pgadmin:

networks:
    shared_network:
        driver: bridge
