---
version: '3.8'
services:

    spark-master:
        build:
            context: .
            dockerfile: Dockerfile-spark
        hostname: ${SPARK_HOST}
        ports:
            - 9090:8080
            - 7077:7077
        volumes:
            - ./spark-apps:/opt/spark-apps
            - ./spark-data:/opt/spark-data
        environment:
            PYSPARK_ALLOW_INSECURE_GATEWAY: 1
            SPARK_LOCAL_IP: ${SPARK_HOST}
            SPARK_LOCAL_HOSTNAME: ${SPARK_HOST}
            SPARK_WORKLOAD: master
            SPARK_MODE: master
        networks:
            - shared_network

    spark-worker:
        scale: 2
        build:
            context: .
            dockerfile: Dockerfile-spark
        volumes:
            - ./spark-apps:/opt/spark-apps
            - ./spark-data:/opt/spark-data
        command: /opt/spark/sbin/start-worker.sh ${SPARK_HOST}:7077
        environment:
            SPARK_MASTER: spark://${SPARK_HOST}:7077
            SPARK_MODE: worker
        networks:   
            - shared_network
