ARG PYTHON_VERSION

FROM python:${PYTHON_VERSION}
ARG AIRFLOW_PROJ_DIR

RUN pip install poetry
RUN mkdir /$AIRFLOW_PROJ_DIR
WORKDIR $AIRFLOW_PROJ_DIR
COPY ./$AIRFLOW_PROJ_DIR/scripts/poetry.lock poetry.lock
COPY ./$AIRFLOW_PROJ_DIR/scripts/pyproject.toml pyproject.toml
RUN poetry install
RUN apt update && apt install -y postgresql-client

COPY ./$AIRFLOW_PROJ_DIR/scripts/entrypoint.sh /
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD []
