"""Address added to User

Revision ID: 73ab563ab716
Revises: 13da6d4368eb
Create Date: 2023-07-03 20:26:34.810507

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "73ab563ab716"
down_revision = "13da6d4368eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("address", sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "address")
    # ### end Alembic commands ###
