---
version: 2.1
orbs:
    python: circleci/python@1.5.0
jobs:
    build-and-test:
        docker:
            - image: cimg/python:3.10.7
        steps:
            - checkout
            - run: whoami
            - run: pkill --help
            - run:
                  name: Install Docker Compose
                  environment:
                      COMPOSE_VERSION: 1.29.2
                  command: |
                      curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
                      chmod +x ~/docker-compose
                      sudo mv ~/docker-compose /usr/local/bin/docker-compose
            - setup_remote_docker
            - run:
                  name: Make env file
                  command: make env_file
            - run:
                  name: Start services
                  command: make start_full_services
            - run:
                  name: Run tests
                  command: docker exec -it backend make test_circleci

workflows:
    buld-and-test:
        jobs:
            - build-and-test
