---
version: 2.1
jobs:
    build-and-test:
        docker:
            - image: python:3.11
            - image: cimg/postgres:14.0
              environment:
                  POSTGRES_USER: postgres
                  POSTGRES_DB: app
                  POSTGRES_PASSWORD: pass
            - image: redis/redis-stack-server
            - image: rabbitmq:latest
            - image: mongo:latest
        resource_class: arm.xlarge
        steps:
            - checkout
            - run: whoami
            - run:
                  name: Create environment variables
                  command: |
                      echo 'export $(grep -v '^#' .circleci/.env_circleci | xargs)' >> "$BASH_ENV"
                      source "$BASH_ENV"
            - run:
                  name: Create environment
                  command: make venv_create
            - run:
                  name: Start celery workers
                  command: make start_celery_workers_detached
            - run:
                  name: Run tests
                  command: make test_parallel

workflows:
    build-and-test:
        jobs:
            - build-and-test
