---
version: 2.1
orbs:
    python: circleci/python@1.5.0
    rust: circleci/rust@1.6.0
jobs:
    build-and-test:
        docker:
            - image: cimg/base:2022.09
            - image: cimg/postgres:14.2
            - image: cimg/redis:6.2.6
            - image: rabbitmq:latest
        steps:
            - checkout
            - run: whoami
            - run:
                  name: wait for db
                  command: dockerize -wait tcp://localhost:5432 -timeout 1m
            - run:
                  name: wait for redis
                  command: dockerize -wait tcp://localhost:6379 -timeout 1m
            - run:
                  name: wait for rabbitmq
                  command: dockerize -wait tcp://localhost:5672 -timeout 1m
            - run:
                  name: make venv
                  command: apt-get install python3-virtualenv && make venv_create
            - run:
                  name: make env_file
                  command: make env_file
            - run:
                  name: Run tests
                  command: make test_parallel

workflows:
    buld-and-test:
        jobs:
            - build-and-test
