---
version: 2.1
orbs:
    python: circleci/python@1.5.0
jobs:
    build-and-test:
        docker:
            - image: cimg/python:3.10.7
            - image: cimg/postgres:14.2
            - image: cimg/redis:6.2.6
            - image: rabbitmq:latest
            - image: mongo:latest
        steps:
            - checkout
            - run: whoami
            - run: pkill --help
            - run:
                  name: wait for db
                  command: dockerize -wait tcp://localhost:5432 -timeout 1m
            - run:
                  name: wait for redis
                  command: dockerize -wait tcp://localhost:6379 -timeout 1m
            - run:
                  name: wait for rabbitmq
                  command: dockerize -wait tcp://localhost:5672 -timeout 1m
            - run:
                  name: wait for mongo
                  command: dockerize -wait tcp://localhost:27017 -timeout 1m
            - run:
                  name: install rust
                  command: make install_rust
            - run:
                  name: make venv
                  command: make venv_create
            - run:
                  name: make env_file
                  command: make env_file
            - run:
                  name: Run tests
                  command: make test_parallel

workflows:
    buld-and-test:
        jobs:
            - build-and-test
