version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.10.2
      - image: postgres:latest
        environment:
          POSTGRES_DB : $CI_POSTGRES_DB
          POSTGRES_USER : $CI_POSTGRES_USER
          POSTGRES_PASSWORD : $CI_POSTGRES_PASSWORD
    steps:
      - checkout
      - run: whoami
      - run: |
          psql --version
      - run:
          name: make venv
          command: make venv_create
      - run:
          name: wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Run tests
          command: make test

workflows:
  sample: 
    jobs:
      - build-and-test
