---
version: 2.1
orbs:
    python: circleci/python@1.5.0
jobs:
    build-and-test:
        docker:
            - image: cimg/python:3.10.7
            - image: cimg/postgres:14.2
            - image: cimg/redis:6.2.6
            - image: rabbitmq:latest
            - image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: pass
        steps:
            - checkout
            - run: whoami
            - run: pkill --help
            - run:
                  name: Create environment variables
                  command: |
                      echo 'export $(grep -v '^#' .env_user | xargs)' >> "$BASH_ENV"
                      echo 'export INTERFACE=localhost' >> "$BASH_ENV"
                      source "$BASH_ENV"
            - run:
                  name: Install Rust
                  command: make install_rust
            - run:
                  name: Create environment
                  command: make venv_create
            - run:
                  name: Start celery workers
                  command: make start_celery_workers_detached
            - run:
                  name: Run tests
                  command: make test_parallel

workflows:
    build-and-test:
        jobs:
            - build-and-test
