version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.10.2
      - image: cimg/postgres:14.2
    steps:
      - checkout
      - run: whoami
      - run: |
          psql --version
      - run:
          name: make venv
          command: make venv_create
      - run:
          name: wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: 
          command: | 
            echo ${TEST}
            echo 'export TEST2=overwritten' >> $BASH_ENV
            echo 'export TEST=overwritten' >> $BASH_ENV
            source $BASH_ENV
            echo ${TEST2}
            echo ${TEST}
          environment:
            TEST: environment_TEST
            TEST2: environment_TEST2
      - run:
          name: Run tests
          command: make test

workflows:
  buld-and-test: 
    jobs:
      - build-and-test
