"""added verified to user

Revision ID: 08747972d220
Revises: b797b4196eb3
Create Date: 2021-07-31 15:47:33.348343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08747972d220'
down_revision = 'b797b4196eb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verified')
    # ### end Alembic commands ###
