"""moved id

Revision ID: 4b16e336a629
Revises: fd028af2242f
Create Date: 2021-08-01 18:57:48.918182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b16e336a629'
down_revision = 'fd028af2242f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
