"""moved id

Revision ID: a07ab730a0e4
Revises: 4b16e336a629
Create Date: 2021-08-01 19:01:58.795773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07ab730a0e4'
down_revision = '4b16e336a629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
