"""moved id

Revision ID: dfcec6aa0a52
Revises: a07ab730a0e4
Create Date: 2021-08-01 19:02:50.708222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfcec6aa0a52'
down_revision = 'a07ab730a0e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
