---
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
    name: spark-pi
    namespace: default
spec:
    type: Python
    mode: cluster
    image: localhost:5000/spark_app
    imagePullPolicy: Always
    mainApplicationFile: local:///apps/udf.py
    arguments: ['10000']
    sparkVersion: 3.1.1
    restartPolicy:
        type: Never
    volumes:
        - name: test-volume
          hostPath:
              path: /tmp
              type: Directory
    driver:
        cores: 1
        coreLimit: 1200m
        memory: 512m
        labels:
            version: 3.1.1
        serviceAccount: my-release-spark
        volumeMounts:
            - name: test-volume
              mountPath: /tmp
    executor:
        cores: 2
        instances: 4
        memory: 512m
        labels:
            version: 3.1.1
        volumeMounts:
            - name: test-volume
              mountPath: /tmp


# helm install my-release spark-operator/spark-operator  --set webhook.enable=true
